In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Variable Name	Role	Type	Demographic	Description	Units	Missing Values
Gender	Feature	Categorical	Gender			no
Age	Feature	Continuous	Age			no
Height	Feature	Continuous				no
Weight	Feature	Continuous				no
family_history_with_overweight	Feature	Binary		Has a family member suffered or suffers from overweight?		no
FAVC	Feature	Binary		Do you eat high caloric food frequently?		no
FCVC	Feature	Integer		Do you usually eat vegetables in your meals?		no
NCP	Feature	Continuous		How many main meals do you have daily?		no
CAEC	Feature	Categorical		Do you eat any food between meals?		no
SMOKE	Feature	Binary		Do you smoke?		no
CH2O	Feature	Continuous		How much water do you drink daily?		no
SCC	Feature	Binary		Do you monitor the calories you eat daily?		no
FAF	Feature	Continuous		How often do you have physical activity?		no
TUE	Feature	Integer		How much time do you use technological devices such as cell phone, videogames, television, computer and others?		no
CALC	Feature	Categorical		How often do you drink alcohol?		no
MTRANS	Feature	Categorical		Which transportation do you usually use?		no
NObeyesdad	Target	Categorical		Obesity level		no

In [2]:
df = pd.read_csv('rawdata.csv')

In [3]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [4]:
features = df.columns.tolist()
features

['Gender',
 'Age',
 'Height',
 'Weight',
 'family_history_with_overweight',
 'FAVC',
 'FCVC',
 'NCP',
 'CAEC',
 'SMOKE',
 'CH2O',
 'SCC',
 'FAF',
 'TUE',
 'CALC',
 'MTRANS',
 'NObeyesdad']

In [5]:
df = pd.get_dummies(df, columns=[
    "MTRANS"
])
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,...,SCC,FAF,TUE,CALC,NObeyesdad,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,...,no,0.0,1.0,no,Normal_Weight,False,False,False,True,False
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,...,yes,3.0,0.0,Sometimes,Normal_Weight,False,False,False,True,False
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,...,no,2.0,1.0,Frequently,Normal_Weight,False,False,False,True,False
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,...,no,2.0,0.0,Frequently,Overweight_Level_I,False,False,False,False,True
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,...,no,0.0,0.0,Sometimes,Overweight_Level_II,False,False,False,True,False

In [6]:
from sklearn.preprocessing import LabelEncoder

target = df['NObeyesdad']
df.drop(columns=['NObeyesdad'],inplace=True)
le = LabelEncoder()
target = le.fit_transform(target)

In [7]:
features = df.columns.tolist()
features

['Gender',
 'Age',
 'Height',
 'Weight',
 'family_history_with_overweight',
 'FAVC',
 'FCVC',
 'NCP',
 'CAEC',
 'SMOKE',
 'CH2O',
 'SCC',
 'FAF',
 'TUE',
 'CALC',
 'MTRANS_Automobile',
 'MTRANS_Bike',
 'MTRANS_Motorbike',
 'MTRANS_Public_Transportation',
 'MTRANS_Walking']

In [8]:
ordinal_mapping = {'no': 0, 'Sometimes': 1, 'Frequently': 2, 'Always': 3}
df['CAEC'] = df['CAEC'].map(ordinal_mapping)
df['CALC'] = df['CALC'].map(ordinal_mapping)

In [9]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_cols = ['Gender', 'family_history_with_overweight', 'FAVC', 'SMOKE', 'SCC']
encoder = OrdinalEncoder()
df[ordinal_cols] = encoder.fit_transform(df[ordinal_cols])

In [10]:
from sklearn.preprocessing import StandardScaler

scale_cols = ['Age', 'Height', 'Weight', 'CH2O', 'FAF', 'CALC', "FCVC", "NCP"]
scaler = StandardScaler()
df[scale_cols] = scaler.fit_transform(df[scale_cols])
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,0.0,-0.522124,-0.875589,-0.862558,1.0,0.0,-0.785019,0.404153,1,0.0,-0.013073,0.0,-1.188039,1.0,-1.419172,False,False,False,True,False
1,0.0,-0.522124,-1.947599,-1.168077,1.0,0.0,1.088342,0.404153,1,1.0,1.618759,1.0,2.339750,0.0,0.521160,False,False,False,True,False
2,1.0,-0.206889,1.054029,-0.366090,1.0,0.0,-0.785019,0.404153,1,0.0,-0.013073,0.0,1.163820,1.0,2.461491,False,False,False,True,False
3,1.0,0.423582,1.054029,0.015808,0.0,0.0,1.088342,0.404153,1,0.0,-0.013073,0.0,1.163820,0.0,2.461491,False,False,False,False,True
4,1.0,-0.364507,0.839627,0.122740,0.0,0.0,-0.785019,-2.167023,1,0.0,-0.013073,0.0,-1.188039,0.0,0.521160,False,False,False,True,False

In [11]:
df['NObeyesdad'] = target

In [12]:
df_gender_0 = df[df['Gender'] == 0.0].copy()
df_gender_1 = df[df['Gender'] == 1.0].copy()

In [13]:
df_gender_0.drop(columns=['Gender'], inplace=True)
df_gender_1.drop(columns=['Gender'], inplace=True)

In [14]:
df_gender_0.shape

(1043, 20)

In [15]:
df_gender_1.shape

(1068, 20)

In [16]:
df_gender_0.to_csv('gender0.csv', index=False)
df_gender_1.to_csv('gender1.csv', index=False)